# Generated by Django 4.0.2 on 2022-03-10 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='parrafo_3',
            field=models.TextField(blank='True', null=True),
        ),
    ]
