# Generated by Django 4.0.2 on 2022-02-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0004_alter_productos_precio'),
    ]

    operations = [
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=250)),
                ('precio', models.IntegerField()),
                ('creacion', models.DateField(auto_now_add=True)),
                ('imagen', models.ImageField(upload_to='menu')),
            ],
        ),
    ]
